CREATE TABLE IF NOT EXISTS `popularities` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  likes INT(8) NOT NULL,
  dislikes INT(8) NOT NULL,
  movie_id INT,
  FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;