CREATE TABLE IF NOT EXISTS `movie_likes` (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  likes TINYINT(1) NOT NULL,
  dislikes TINYINT(1) NOT NULL,
  movie_id INT,
  FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;